### PR TITLE
Add extended TPF QS paper

### PR DESCRIPTION
**Pull request by rubensworks**
Perhaps the original paper should be removed from the list, but I left it here for now for the sake of completeness.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Looks good to me; strange compilation error though (which seems unrelated to your edit). Let me retrigger the build. Seems like an error with a new package version.

**Comment by rubensworks** [comment]
Strange error indeed.
Compiling locally using ruby 2.3.0 seems to work just fine.

**Comment by RubenVerborgh** [comment]
Managed to reproduce; when you update all gems to the latest version, it fails. Now finding the culprit.

**Comment by RubenVerborgh** [comment]
@rubensworks Can you rebase on `master`? Should be fixed.

**Comment by rubensworks** [comment]
Ok, that seems to have fixed it! :)

**Pull request merged**
